version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  grafana:
    build: './grafana'
    restart: always
    container_name: grafana_container
    ports:
      - "3000:3000"
  application:
    build: ./
    restart: always
    container_name: application_container
    healthcheck:
      test: curl --fail -s http://localhost:8080/api/common/ping || exit 1
      interval: 1m30s
      timeout: 2s
      retries: 1
    depends_on:
      - db
    ports:
      - "8080:8080"
