apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: pg_container:5432
    database: test_db
    user: root
    secureJsonData:
      password: 'root'
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false