create table sys_parameter
(
    id        bigint generated by default as identity
        primary key,
    name      varchar(255),
    profile   varchar(255),
    value     varchar(255),
    constraint parameter_profile_unique unique (name, profile)
);

create table sys_patient
(
    id            bigint generated by default as identity
        primary key,
    address       varchar(255),
    age           integer                  not null,
    blood_type    varchar(255),
    city          varchar(255),
    color         varchar(255),
    cpf           varchar(14)
        constraint cpf_unique
            unique,
    date_of_birth timestamp with time zone not null,
    district      varchar(255),
    email         varchar(255),
    father        varchar(255),
    gender        varchar(255),
    height        varchar(255),
    mobile_phone  varchar(15),
    mother        varchar(255),
    name          varchar(255),
    number        varchar(255),
    password      varchar(255),
    phone         varchar(14),
    rg            varchar(255),
    state         varchar(2),
    weigth        real                     not null,
    zip_code      varchar(9),
    zodiac        varchar(255)
);

create table sys_reading_type
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

create table sys_reading
(
    id              bigint generated by default as identity
        primary key,
    date            timestamp with time zone not null,
    value           double precision         not null,
    patient_id      bigint
        constraint patient_fk
            references sys_patient,
    reading_type_id bigint
        constraint reading_type_fk
            references sys_reading_type
);
